language: ruby
cache: bundler
sudo: required
os:
  - linux
addons:
  apt:
    packages:
      - gdb
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system
  - gem install bundler
  - gem --version
